# config/services.yaml

parameters:
    # paramètres généraux si besoin

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # injecte automatiquement les dépendances
        autoconfigure: true # enregistre automatiquement les services pour commandes, événements, etc.

    # ajoute explicitement ton repository avec le tag doctrine
    App\Repository\RoleRepository:
        tags: ['doctrine.repository_service']

    # rend toutes les classes de src/ disponibles comme services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DataPersister/*'
            - '../src/Repository/*' # les repositories sont déjà déclarés explicitement
